
//------------------------------------------------------------------------------
// <auto-generated>
// by mehrang 
// </auto-generated>
//------------------------------------------------------------------------------

using System;

using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

using System.Collections.Generic;

using DataLayer.Miscellaneous;


namespace DataLayer.Contract
{
    public interface IContract
    {
        global::System.Int32 Id { get; set; }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Access")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class AccessContract : IContract
    {
        public AccessContract()
        {
        }

        [Filed("Access", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Access", "DisplayMode")]
        public global::System.Int64 DisplayMode { get; set; }




        [Filed("Access", "Role")]
        public string Role { get; set; }

        [Filed("Access", "IEnumerableRole")]
        public IEnumerable<SelectListItem> IEnumerableRole { get; set; }

        [Filed("Access", "FK_Role")]
        public global::System.Int32 FK_Role { get; set; }



        [Filed("Access", "Filed")]
        public string Filed { get; set; }

        [Filed("Access", "IEnumerableFiled")]
        public IEnumerable<SelectListItem> IEnumerableFiled { get; set; }

        [Filed("Access", "FK_Filed")]
        public global::System.Int32 FK_Filed { get; set; }

        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Accounting")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class AccountingContract : IContract
    {


        [Filed("Accounting", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Accounting", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Accounting", "Debtor")]
        public global::System.Decimal Debtor { get; set; }




        [Filed("Accounting", "Creditor")]
        public global::System.Decimal Creditor { get; set; }




        [Filed("Accounting", "User")]
        public string User { get; set; }

        [Filed("Accounting", "IEnumerableUser")]
        public IEnumerable<SelectListItem> IEnumerableUser { get; set; }

        [Filed("Accounting", "FK_User")]
        public global::System.Int32 FK_User { get; set; }



        [Filed("Accounting", "Invoice")]
        public string Invoice { get; set; }

        [Filed("Accounting", "IEnumerableInvoice")]
        public IEnumerable<SelectListItem> IEnumerableInvoice { get; set; }

        [Filed("Accounting", "FK_Invoice")]
        public global::System.Int32 FK_Invoice { get; set; }



        [Filed("Accounting", "Date")]
        public global::System.String Date { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Bridge_BusinessOwner_Marketer")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class Bridge_BusinessOwner_MarketerContract : IContract
    {


        [Filed("Bridge_BusinessOwner_Marketer", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Bridge_BusinessOwner_Marketer", "BusinessOwner")]
        public string BusinessOwner { get; set; }

        [Filed("Bridge_BusinessOwner_Marketer", "IEnumerableBusinessOwner")]
        public IEnumerable<SelectListItem> IEnumerableBusinessOwner { get; set; }

        [Filed("Bridge_BusinessOwner_Marketer", "FK_BusinessOwner")]
        public global::System.Int32 FK_BusinessOwner { get; set; }



        [Filed("Bridge_BusinessOwner_Marketer", "Marketer")]
        public string Marketer { get; set; }

        [Filed("Bridge_BusinessOwner_Marketer", "IEnumerableMarketer")]
        public IEnumerable<SelectListItem> IEnumerableMarketer { get; set; }

        [Filed("Bridge_BusinessOwner_Marketer", "FK_Marketer")]
        public global::System.Int32 FK_Marketer { get; set; }



        [Filed("Bridge_BusinessOwner_Marketer", "DiscriptionRequest")]
        public global::System.String DiscriptionRequest { get; set; }




        [Filed("Bridge_BusinessOwner_Marketer", "AcceptRequest")]
        public Nullable<global::System.Boolean> AcceptRequest { get; set; }




        [Filed("Bridge_BusinessOwner_Marketer", "RequestFromBusinessOwner")]
        public Nullable<global::System.Boolean> RequestFromBusinessOwner { get; set; }




        [Filed("Bridge_BusinessOwner_Marketer", "RequestFromMarketer")]
        public Nullable<global::System.Boolean> RequestFromMarketer { get; set; }




        [Filed("Bridge_BusinessOwner_Marketer", "RejectRequest")]
        public Nullable<global::System.Boolean> RejectRequest { get; set; }




        [Filed("Bridge_BusinessOwner_Marketer", "date")]
        public global::System.String date { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Bridge_Invoice_Product")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class Bridge_Invoice_ProductContract : IContract
    {


        [Filed("Bridge_Invoice_Product", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Bridge_Invoice_Product", "Count")]
        public global::System.Int32 Count { get; set; }




        [Filed("Bridge_Invoice_Product", "Product")]
        public string Product { get; set; }

        [Filed("Bridge_Invoice_Product", "IEnumerableProduct")]
        public IEnumerable<SelectListItem> IEnumerableProduct { get; set; }

        [Filed("Bridge_Invoice_Product", "FK_Product")]
        public global::System.Int32 FK_Product { get; set; }



        [Filed("Bridge_Invoice_Product", "Invoice")]
        public string Invoice { get; set; }

        [Filed("Bridge_Invoice_Product", "IEnumerableInvoice")]
        public IEnumerable<SelectListItem> IEnumerableInvoice { get; set; }

        [Filed("Bridge_Invoice_Product", "FK_Invoice")]
        public global::System.Int32 FK_Invoice { get; set; }

        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Bridge_Province_BusinessOwner")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class Bridge_Province_BusinessOwnerContract : IContract
    {


        [Filed("Bridge_Province_BusinessOwner", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Bridge_Province_BusinessOwner", "Province")]
        public string Province { get; set; }

        [Filed("Bridge_Province_BusinessOwner", "IEnumerableProvince")]
        public IEnumerable<SelectListItem> IEnumerableProvince { get; set; }

        [Filed("Bridge_Province_BusinessOwner", "FK_Province")]
        public global::System.Int32 FK_Province { get; set; }



        [Filed("Bridge_Province_BusinessOwner", "BusinessOwner")]
        public string BusinessOwner { get; set; }

        [Filed("Bridge_Province_BusinessOwner", "IEnumerableBusinessOwner")]
        public IEnumerable<SelectListItem> IEnumerableBusinessOwner { get; set; }

        [Filed("Bridge_Province_BusinessOwner", "FK_BusinessOwner")]
        public global::System.Int32 FK_BusinessOwner { get; set; }



        [Filed("Bridge_Province_BusinessOwner", "AnyXKG")]
        public global::System.Int32 AnyXKG { get; set; }




        [Filed("Bridge_Province_BusinessOwner", "AnyXKGMony")]
        public global::System.Decimal AnyXKGMony { get; set; }




        [Filed("Bridge_Province_BusinessOwner", "FreeGratherThanMony")]
        public Nullable<global::System.Decimal> FreeGratherThanMony { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="BusinessOwner")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class BusinessOwnerContract : IContract
    {

        [Filed("BusinessOwner", "LinkInvoice")]
        public string LinkInvoice { get { return "Invoice"; } }

        [Filed("BusinessOwner", "LinkBridge_BusinessOwner_Marketer")]
        public string LinkBridge_BusinessOwner_Marketer { get { return "Bridge_BusinessOwner_Marketer"; } }

        [Filed("BusinessOwner", "LinkBridge_Province_BusinessOwner")]
        public string LinkBridge_Province_BusinessOwner { get { return "Bridge_Province_BusinessOwner"; } }

        [Filed("BusinessOwner", "LinkProduct")]
        public string LinkProduct { get { return "Product"; } }


        [Filed("BusinessOwner", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("BusinessOwner", "Name")]
        public global::System.String Name { get; set; }




        [Filed("BusinessOwner", "TypeActivity")]
        public global::System.String TypeActivity { get; set; }




        [Filed("BusinessOwner", "WordKey")]
        public global::System.String WordKey { get; set; }




        [Filed("BusinessOwner", "Address")]
        public global::System.String Address { get; set; }




        [Filed("BusinessOwner", "NationalCode")]
        public global::System.String NationalCode { get; set; }




        [Filed("BusinessOwner", "User")]
        public string User { get; set; }

        [Filed("BusinessOwner", "IEnumerableUser")]
        public IEnumerable<SelectListItem> IEnumerableUser { get; set; }

        [Filed("BusinessOwner", "FK_User")]
        public global::System.Int32 FK_User { get; set; }



        [Filed("BusinessOwner", "Province")]
        public string Province { get; set; }

        [Filed("BusinessOwner", "IEnumerableProvince")]
        public IEnumerable<SelectListItem> IEnumerableProvince { get; set; }

        [Filed("BusinessOwner", "FK_Province")]
        public global::System.Int32 FK_Province { get; set; }



        [Filed("BusinessOwner", "Marketer")]
        public string Marketer { get; set; }

        [Filed("BusinessOwner", "IEnumerableMarketer")]
        public IEnumerable<SelectListItem> IEnumerableMarketer { get; set; }

        [Filed("BusinessOwner", "FK_Marketer")]
        public Nullable<global::System.Int32> FK_Marketer { get; set; }



        [Filed("BusinessOwner", "DocumentFile")]
        public global::System.String DocumentFile { get; set; }




        [Filed("BusinessOwner", "Image")]
        public global::System.String Image { get; set; }




        [Filed("BusinessOwner", "WebSiteAddress")]
        public global::System.String WebSiteAddress { get; set; }




        [Filed("BusinessOwner", "Discription")]
        public global::System.String Discription { get; set; }




        [Filed("BusinessOwner", "Active")]
        public Nullable<global::System.Boolean> Active { get; set; }




        [Filed("BusinessOwner", "Tel")]
        public global::System.String Tel { get; set; }




        [Filed("BusinessOwner", "Yahoo")]
        public global::System.String Yahoo { get; set; }




        [Filed("BusinessOwner", "Gmail")]
        public global::System.String Gmail { get; set; }




        [Filed("BusinessOwner", "Skype")]
        public global::System.String Skype { get; set; }




        [Filed("BusinessOwner", "PaymentPorsantAmount")]
        public Nullable<global::System.Decimal> PaymentPorsantAmount { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class CategoryContract : IContract
    {

        [Filed("Category", "LinkCategory")]
        public string LinkCategory { get { return "Category"; } }

        [Filed("Category", "LinkProduct")]
        public string LinkProduct { get { return "Product"; } }


        [Filed("Category", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Category", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Category", "Discription")]
        public global::System.String Discription { get; set; }




        [Filed("Category", "Category")]
        public string Category { get; set; }

        [Filed("Category", "IEnumerableCategory")]
        public IEnumerable<SelectListItem> IEnumerableCategory { get; set; }

        [Filed("Category", "FK_Category")]
        public Nullable<global::System.Int32> FK_Category { get; set; }

        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }

        public bool HaveProduct { get; set; }
        public string IdsParent { get; set; }
        public string Image_ForOrderByUse { get; set; }
        public string TitlePage { get; set; }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="CategorySetting")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class CategorySettingContract : IContract
    {

        [Filed("CategorySetting", "LinkSetting")]
        public string LinkSetting { get { return "Setting"; } }


        [Filed("CategorySetting", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("CategorySetting", "Name")]
        public global::System.String Name { get; set; }




        [Filed("CategorySetting", "GroupName")]
        public global::System.String GroupName { get; set; }




        [Filed("CategorySetting", "Discription")]
        public global::System.String Discription { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class CommentContract : IContract
    {

        [Filed("Comment", "LinkComment")]
        public string LinkComment { get { return "Comment"; } }


        [Filed("Comment", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Comment", "Comment")]
        public string Comment { get; set; }

        [Filed("Comment", "IEnumerableComment")]
        public IEnumerable<SelectListItem> IEnumerableComment { get; set; }

        [Filed("Comment", "FK_Comment")]
        public Nullable<global::System.Int32> FK_Comment { get; set; }



        [Filed("Comment", "KeyWord")]
        public global::System.String KeyWord { get; set; }




        [Filed("Comment", "Comment1")]
        public global::System.String Comment1 { get; set; }




        [Filed("Comment", "VotePositive")]
        public Nullable<global::System.Int32> VotePositive { get; set; }




        [Filed("Comment", "ComputerIp")]
        public global::System.String ComputerIp { get; set; }




        [Filed("Comment", "Active")]
        public Nullable<global::System.Boolean> Active { get; set; }




        [Filed("Comment", "Product")]
        public string Product { get; set; }

        [Filed("Comment", "IEnumerableProduct")]
        public IEnumerable<SelectListItem> IEnumerableProduct { get; set; }

        [Filed("Comment", "FK_Product")]
        public Nullable<global::System.Int32> FK_Product { get; set; }



        [Filed("Comment", "CommentType")]
        public Nullable<global::System.Int16> CommentType { get; set; }




        [Filed("Comment", "VoteNegative")]
        public Nullable<global::System.Int32> VoteNegative { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Content")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class ContentContract : IContract
    {


        [Filed("Content", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Content", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Content", "ShowValue")]
        public global::System.String ShowValue { get; set; }




        [Filed("Content", "PartialType")]
        public global::System.String PartialType { get; set; }




        [Filed("Content", "Width")]
        public Nullable<global::System.Int16> Width { get; set; }




        [Filed("Content", "Position")]
        public Nullable<global::System.Int16> Position { get; set; }




        [Filed("Content", "ContentType")]
        public Nullable<global::System.Int16> ContentType { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Entity")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class EntityContract : IContract
    {

        [Filed("Entity", "LinkFiled")]
        public string LinkFiled { get { return "Filed"; } }


        [Filed("Entity", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Entity", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Entity", "PersianName")]
        public global::System.String PersianName { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Filed")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class FiledContract : IContract
    {

        [Filed("Filed", "LinkAccess")]
        public string LinkAccess { get { return "Access"; } }

        [Filed("Filed", "LinkLanguge")]
        public string LinkLanguge { get { return "Languge"; } }


        [Filed("Filed", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Filed", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Filed", "PartialType")]
        public Nullable<global::System.Int16> PartialType { get; set; }




        [Filed("Filed", "OrderByValue")]
        public global::System.Int16 OrderByValue { get; set; }




        [Filed("Filed", "Entity")]
        public string Entity { get; set; }

        [Filed("Filed", "IEnumerableEntity")]
        public IEnumerable<SelectListItem> IEnumerableEntity { get; set; }

        [Filed("Filed", "FK_Entity")]
        public global::System.Int32 FK_Entity { get; set; }

        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Invoice")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class InvoiceContract : IContract
    {

        [Filed("Invoice", "LinkAccounting")]
        public string LinkAccounting { get { return "Accounting"; } }

        [Filed("Invoice", "LinkBridge_Invoice_Product")]
        public string LinkBridge_Invoice_Product { get { return "Bridge_Invoice_Product"; } }


        [Filed("Invoice", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Invoice", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Invoice", "Date")]
        public global::System.String Date { get; set; }




        [Filed("Invoice", "State")]
        public global::System.Byte State { get; set; }




        [Filed("Invoice", "DeliveryAddress")]
        public global::System.String DeliveryAddress { get; set; }




        [Filed("Invoice", "MoneySum")]
        public Nullable<global::System.Decimal> MoneySum { get; set; }




        [Filed("Invoice", "Discount")]
        public Nullable<global::System.Decimal> Discount { get; set; }




        [Filed("Invoice", "Shipping")]
        public Nullable<global::System.Decimal> Shipping { get; set; }




        [Filed("Invoice", "PaymentSum")]
        public Nullable<global::System.Decimal> PaymentSum { get; set; }




        [Filed("Invoice", "PaymentToCountinue")]
        public Nullable<global::System.Decimal> PaymentToCountinue { get; set; }




        [Filed("Invoice", "User")]
        public string User { get; set; }

        [Filed("Invoice", "IEnumerableUser")]
        public IEnumerable<SelectListItem> IEnumerableUser { get; set; }

        [Filed("Invoice", "FK_User")]
        public global::System.Int32 FK_User { get; set; }



        [Filed("Invoice", "BusinessOwner")]
        public string BusinessOwner { get; set; }

        [Filed("Invoice", "IEnumerableBusinessOwner")]
        public IEnumerable<SelectListItem> IEnumerableBusinessOwner { get; set; }

        [Filed("Invoice", "FK_BusinessOwner")]
        public global::System.Int32 FK_BusinessOwner { get; set; }



        [Filed("Invoice", "type")]
        public Nullable<global::System.Int16> type { get; set; }




        [Filed("Invoice", "DeliveryCode")]
        public global::System.String DeliveryCode { get; set; }




        [Filed("Invoice", "DeliveryCodedUnPerfect")]
        public global::System.String DeliveryCodedUnPerfect { get; set; }




        [Filed("Invoice", "NoteForBusinessOwner")]
        public global::System.String NoteForBusinessOwner { get; set; }




        [Filed("Invoice", "NoteForUser")]
        public global::System.String NoteForUser { get; set; }




        [Filed("Invoice", "Marketer")]
        public string Marketer { get; set; }

        [Filed("Invoice", "IEnumerableMarketer")]
        public IEnumerable<SelectListItem> IEnumerableMarketer { get; set; }

        [Filed("Invoice", "FK_Marketer")]
        public Nullable<global::System.Int32> FK_Marketer { get; set; }



        [Filed("Invoice", "Province")]
        public string Province { get; set; }

        [Filed("Invoice", "IEnumerableProvince")]
        public IEnumerable<SelectListItem> IEnumerableProvince { get; set; }

        [Filed("Invoice", "FK_Province")]
        public Nullable<global::System.Int32> FK_Province { get; set; }



        [Filed("Invoice", "VoteBusinessOwner")]
        public Nullable<global::System.Boolean> VoteBusinessOwner { get; set; }




        [Filed("Invoice", "VoteMarketer")]
        public Nullable<global::System.Boolean> VoteMarketer { get; set; }




        [Filed("Invoice", "Time")]
        public global::System.String Time { get; set; }




        [Filed("Invoice", "PaymentBankCode")]
        public Nullable<global::System.Int16> PaymentBankCode { get; set; }




        [Filed("Invoice", "TransctionRefrenceId")]
        public global::System.String TransctionRefrenceId { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Languge")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class LangugeContract : IContract
    {


        [Filed("Languge", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Languge", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Languge", "Value")]
        public global::System.String Value { get; set; }




        [Filed("Languge", "Title")]
        public global::System.String Title { get; set; }




        [Filed("Languge", "Filed")]
        public string Filed { get; set; }

        [Filed("Languge", "IEnumerableFiled")]
        public IEnumerable<SelectListItem> IEnumerableFiled { get; set; }

        [Filed("Languge", "FK_Filed")]
        public global::System.Int32 FK_Filed { get; set; }

        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Marketer")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class MarketerContract : IContract
    {

        [Filed("Marketer", "LinkInvoice")]
        public string LinkInvoice { get { return "Invoice"; } }

        [Filed("Marketer", "LinkBridge_BusinessOwner_Marketer")]
        public string LinkBridge_BusinessOwner_Marketer { get { return "Bridge_BusinessOwner_Marketer"; } }

        [Filed("Marketer", "LinkBusinessOwner")]
        public string LinkBusinessOwner { get { return "BusinessOwner"; } }

        [Filed("Marketer", "LinkMarketer")]
        public string LinkMarketer { get { return "Marketer"; } }


        [Filed("Marketer", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Marketer", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Marketer", "Specialty")]
        public global::System.String Specialty { get; set; }




        [Filed("Marketer", "WordKey")]
        public global::System.String WordKey { get; set; }




        [Filed("Marketer", "User")]
        public string User { get; set; }

        [Filed("Marketer", "IEnumerableUser")]
        public IEnumerable<SelectListItem> IEnumerableUser { get; set; }

        [Filed("Marketer", "FK_User")]
        public global::System.Int32 FK_User { get; set; }



        [Filed("Marketer", "Marketer")]
        public string Marketer { get; set; }

        [Filed("Marketer", "IEnumerableMarketer")]
        public IEnumerable<SelectListItem> IEnumerableMarketer { get; set; }

        [Filed("Marketer", "FK_Marketer")]
        public Nullable<global::System.Int32> FK_Marketer { get; set; }



        [Filed("Marketer", "Image")]
        public global::System.String Image { get; set; }




        [Filed("Marketer", "WebSiteAddress")]
        public global::System.String WebSiteAddress { get; set; }




        [Filed("Marketer", "Tel")]
        public global::System.String Tel { get; set; }




        [Filed("Marketer", "Active")]
        public Nullable<global::System.Boolean> Active { get; set; }




        [Filed("Marketer", "Yahoo")]
        public global::System.String Yahoo { get; set; }




        [Filed("Marketer", "Gmail")]
        public global::System.String Gmail { get; set; }




        [Filed("Marketer", "Skype")]
        public global::System.String Skype { get; set; }




        [Filed("Marketer", "PaymentPorsantAmount")]
        public Nullable<global::System.Decimal> PaymentPorsantAmount { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Message")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class MessageContract : IContract
    {


        [Filed("Message", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Message", "UseSender")]
        public string UseSender { get; set; }

        [Filed("Message", "IEnumerableUseSender")]
        public IEnumerable<SelectListItem> IEnumerableUseSender { get; set; }

        [Filed("Message", "FK_UseSender")]
        public global::System.Int32 FK_UseSender { get; set; }



        [Filed("Message", "UserReceiver")]
        public string UserReceiver { get; set; }

        [Filed("Message", "IEnumerableUserReceiver")]
        public IEnumerable<SelectListItem> IEnumerableUserReceiver { get; set; }

        [Filed("Message", "FK_UserReceiver")]
        public global::System.Int32 FK_UserReceiver { get; set; }



        [Filed("Message", "Date")]
        public global::System.String Date { get; set; }




        [Filed("Message", "Readed")]
        public global::System.Boolean Readed { get; set; }




        [Filed("Message", "Text")]
        public global::System.String Text { get; set; }




        [Filed("Message", "type")]
        public Nullable<global::System.Int16> type { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }

    public partial class DisputeResolutionContract : IContract
    {
        public int Id { get; set; }

        public int FkInvoice { get; set; }

        public int? FkUser { get; set; }

        public int? FkBusinessOwner { get; set; }

        public int? FkMarketer { get; set; }

        public short Writer { get; set; }
        [Required]
        [StringLength(1000)]
        public string Discription { get; set; }
        [StringLength(100)]
        public string FileDocumentAdress { get; set; }
        [Required]
        [StringLength(10)]
        public string Date { get; set; }
        public short? DisputerwhoPerson { get; set; }

    }



    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class ProductContract : IContract
    {

        [Filed("Product", "LinkBridge_Invoice_Product")]
        public string LinkBridge_Invoice_Product { get { return "Bridge_Invoice_Product"; } }

        [Filed("Product", "LinkComment")]
        public string LinkComment { get { return "Comment"; } }


        [Filed("Product", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Product", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Product", "Brand")]
        public global::System.String Brand { get; set; }




        [Filed("Product", "Image")]
        public global::System.String Image { get; set; }




        [Filed("Product", "Image1")]
        public global::System.String Image1 { get; set; }




        [Filed("Product", "Image2")]
        public global::System.String Image2 { get; set; }




        [Filed("Product", "Price")]
        public global::System.Decimal Price { get; set; }




        [Filed("Product", "RegisterDate")]
        public global::System.String RegisterDate { get; set; }




        [Filed("Product", "Discription")]
        public global::System.String Discription { get; set; }




        [Filed("Product", "BusinessOwner")]
        public string BusinessOwner { get; set; }

        [Filed("Product", "IEnumerableBusinessOwner")]
        public IEnumerable<SelectListItem> IEnumerableBusinessOwner { get; set; }

        [Filed("Product", "FK_BusinessOwner")]
        public global::System.Int32 FK_BusinessOwner { get; set; }



        [Filed("Product", "MadeInCountry")]
        public global::System.String MadeInCountry { get; set; }




        [Filed("Product", "CountPrice")]
        public Nullable<global::System.Decimal> CountPrice { get; set; }




        [Filed("Product", "MinCountForPrice")]
        public Nullable<global::System.Int32> MinCountForPrice { get; set; }




        [Filed("Product", "available")]
        public global::System.Int32 available { get; set; }




        [Filed("Product", "PersentMarkater")]
        public global::System.Single PersentMarkater { get; set; }




        [Filed("Product", "AcceptReturnDay")]
        public Nullable<global::System.Byte> AcceptReturnDay { get; set; }




        [Filed("Product", "ShippingDiscription")]
        public global::System.String ShippingDiscription { get; set; }




        [Filed("Product", "WordKey")]
        public global::System.String WordKey { get; set; }




        [Filed("Product", "SellOrBuy")]
        public global::System.Boolean SellOrBuy { get; set; }




        [Filed("Product", "UnitBuy")]
        public global::System.String UnitBuy { get; set; }




        [Filed("Product", "wightUnitBuyWithKG")]
        public double wightUnitBuyWithKG { get; set; }




        [Filed("Product", "Active")]
        public Nullable<global::System.Boolean> Active { get; set; }




        [Filed("Product", "Category")]
        public string Category { get; set; }

        [Filed("Product", "IEnumerableCategory")]
        public IEnumerable<SelectListItem> IEnumerableCategory { get; set; }

        [Filed("Product", "FK_Category")]
        public Nullable<global::System.Int32> FK_Category { get; set; }

        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }

        public string Dimansion { get; set; }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Province")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class ProvinceContract : IContract
    {

        [Filed("Province", "LinkInvoice")]
        public string LinkInvoice { get { return "Invoice"; } }

        [Filed("Province", "LinkBridge_Province_BusinessOwner")]
        public string LinkBridge_Province_BusinessOwner { get { return "Bridge_Province_BusinessOwner"; } }

        [Filed("Province", "LinkBusinessOwner")]
        public string LinkBusinessOwner { get { return "BusinessOwner"; } }


        [Filed("Province", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Province", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Province", "Country")]
        public global::System.String Country { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class RoleContract : IContract
    {

        [Filed("Role", "LinkAccess")]
        public string LinkAccess { get { return "Access"; } }

        [Filed("Role", "LinkUser")]
        public string LinkUser { get { return "User"; } }


        [Filed("Role", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Role", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Role", "Discription")]
        public global::System.String Discription { get; set; }




        [Filed("Role", "Type")]
        public Nullable<global::System.Int16> Type { get; set; }


        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="Setting")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class SettingContract : IContract
    {


        [Filed("Setting", "Id")]
        public global::System.Int32 Id { get; set; }




        [Filed("Setting", "Name")]
        public global::System.String Name { get; set; }




        [Filed("Setting", "Value")]
        public global::System.String Value { get; set; }




        [Filed("Setting", "Value2")]
        public global::System.String Value2 { get; set; }




        [Filed("Setting", "CategorySetting")]
        public string CategorySetting { get; set; }

        [Filed("Setting", "IEnumerableCategorySetting")]
        public IEnumerable<SelectListItem> IEnumerableCategorySetting { get; set; }

        [Filed("Setting", "FK_CategorySetting")]
        public global::System.Int32 FK_CategorySetting { get; set; }

        [Filed("Filed", "btnFormSubmit")]
        public string btnFormSubmit { get { return "btnFormSubmit"; } }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[EdmEntityTypeAttribute(NamespaceName="ShoppingCentersModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]

    public partial class UserContract : IContract
    {
        [Filed("User", "Id")]
        public global::System.Int32 Id { get; set; }

        [Filed("User", "Mobile")]
        public global::System.String Mobile { get; set; }

        [Filed("User", "RegisterDate")]
        public global::System.String RegisterDate { get; set; }

        [Filed("User", "FK_Role")]
        public global::System.Int32 FK_Role { get; set; }

        [Filed("User", "IpComputer")]
        public global::System.String IpComputer { get; set; }

        [Filed("User", "Ative")]
        public Nullable<global::System.Boolean> Ative { get; set; }


    }



}
