
//------------------------------------------------------------------------------
// <auto-generated>
// by mehrang 
// </auto-generated>
//------------------------------------------------------------------------------

/*



    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Abs_AccountingEntity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Abs_AccountingEntity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='NameAndFamilyOwner' And Accsess.Entity.Name ='Abs_AccountingEntity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Tel_1' And Accsess.Entity.Name ='Abs_AccountingEntity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Tel_2' And Accsess.Entity.Name ='Abs_AccountingEntity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Mobile' And Accsess.Entity.Name ='Abs_AccountingEntity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Email' And Accsess.Entity.Name ='Abs_AccountingEntity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='CityName' And Accsess.Entity.Name ='Abs_AccountingEntity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Address' And Accsess.Entity.Name ='Abs_AccountingEntity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='RegisterDate' And Accsess.Entity.Name ='Abs_AccountingEntity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'تاریخ ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Province' And Accsess.Entity.Name ='Abs_AccountingEntity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Access'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='DisplayMode' And Accsess.Entity.Name ='Access'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Role' And Accsess.Entity.Name ='Access'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Filed' And Accsess.Entity.Name ='Access'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Bridge_Category_Product'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Category' And Accsess.Entity.Name ='Bridge_Category_Product'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Product' And Accsess.Entity.Name ='Bridge_Category_Product'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Bridge_Document_BusinessOwner'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Document' And Accsess.Entity.Name ='Bridge_Document_BusinessOwner'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Debtor' And Accsess.Entity.Name ='Bridge_Document_BusinessOwner'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='creditor' And Accsess.Entity.Name ='Bridge_Document_BusinessOwner'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Abs_AccountingEntity' And Accsess.Entity.Name ='Bridge_Document_BusinessOwner'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Bridge_Invoice_Product'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Product' And Accsess.Entity.Name ='Bridge_Invoice_Product'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Invoice' And Accsess.Entity.Name ='Bridge_Invoice_Product'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Count' And Accsess.Entity.Name ='Bridge_Invoice_Product'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='BusinessOwner'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Category'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Category'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Discription' And Accsess.Entity.Name ='Category'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Category' And Accsess.Entity.Name ='Category'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='CategorySetting'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='CategorySetting'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='GroupName' And Accsess.Entity.Name ='CategorySetting'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Discription' And Accsess.Entity.Name ='CategorySetting'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Content'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Content'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='PartialType' And Accsess.Entity.Name ='Content'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Width' And Accsess.Entity.Name ='Content'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Position' And Accsess.Entity.Name ='Content'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='priority' And Accsess.Entity.Name ='Content'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='DisplayMode' And Accsess.Entity.Name ='Content'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Role' And Accsess.Entity.Name ='Content'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Entity' And Accsess.Entity.Name ='Content'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Document'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Document'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Date' And Accsess.Entity.Name ='Document'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'تاریخ ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Invoice' And Accsess.Entity.Name ='Document'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='RefrenceNumber' And Accsess.Entity.Name ='Document'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Entity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Entity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='PersianName' And Accsess.Entity.Name ='Entity'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Filed'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Filed'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='PartialType' And Accsess.Entity.Name ='Filed'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Entity' And Accsess.Entity.Name ='Filed'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Invoice'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Invoice'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Date' And Accsess.Entity.Name ='Invoice'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'تاریخ ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='PaymentSum' And Accsess.Entity.Name ='Invoice'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='State' And Accsess.Entity.Name ='Invoice'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Languge'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Languge'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Value' And Accsess.Entity.Name ='Languge'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Active' And Accsess.Entity.Name ='Languge'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Filed' And Accsess.Entity.Name ='Languge'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Marketer'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Specialty' And Accsess.Entity.Name ='Marketer'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Product'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Product'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Discription' And Accsess.Entity.Name ='Product'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_BusinessOwner' And Accsess.Entity.Name ='Product'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Province'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Province'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='country' And Accsess.Entity.Name ='Province'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Role'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Role'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Discription' And Accsess.Entity.Name ='Role'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='Setting'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='Setting'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Value' And Accsess.Entity.Name ='Setting'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Fk_CategorySetting' And Accsess.Entity.Name ='Setting'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Id' And Accsess.Entity.Name ='User'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'شناسه ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Name' And Accsess.Entity.Name ='User'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'نام ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Family' And Accsess.Entity.Name ='User'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Tel' And Accsess.Entity.Name ='User'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Mobile' And Accsess.Entity.Name ='User'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Email' And Accsess.Entity.Name ='User'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='CityName' And Accsess.Entity.Name ='User'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Address' And Accsess.Entity.Name ='User'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='RegisterDate' And Accsess.Entity.Name ='User'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'تاریخ ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='Fk_Province' And Accsess.Entity.Name ='User'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
     
    DECLARE @FK_Filed int;
    SELECT top 1 @FK_Filed=Accsess.Filed.Id   FROM [ShoppingCenters].[Accsess].[Filed]
    join [ShoppingCenters].[Accsess].Entity  on Accsess.Filed.FK_Entity=Accsess.Entity.Id 
     where Accsess.Filed.Name='FK_Role' And Accsess.Entity.Name ='User'
    INSERT INTO [ShoppingCenters].[Accsess].[Languge]
               ([Name] ,[Value],[Active],[FK_Filed])
         VALUES
               ('Persian',N'حسن ',1,@FK_Filed)
    GO
     
    
    */
    

