
//------------------------------------------------------------------------------
// <auto-generated>
// by mehrang 
// </auto-generated>
//------------------------------------------------------------------------------

/*



    
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Access','Access',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Accounting','Accounting',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Bridge_BusinessOwner_Marketer','Bridge_BusinessOwner_Marketer',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Bridge_Invoice_Product','Bridge_Invoice_Product',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Bridge_Province_BusinessOwner','Bridge_Province_BusinessOwner',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('BusinessOwner','BusinessOwner',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Category','Category',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('CategorySetting','CategorySetting',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Comment','Comment',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Content','Content',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('DisputeResolution','DisputeResolution',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Entity','Entity',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Filed','Filed',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Invoice','Invoice',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Languge','Languge',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Marketer','Marketer',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Message','Message',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Product','Product',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Province','Province',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Role','Role',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('Setting','Setting',1)
    GO
    
    INSERT INTO [ShoppingCenters].[Miscellaneous].[Setting]
               ([Name]
               ,[Value]
               ,[Fk_CategorySetting])
         VALUES
               ('User','User',1)
    GO
    */
    

