
//------------------------------------------------------------------------------
// <auto-generated>
// by mehrang 
// </auto-generated>
//------------------------------------------------------------------------------

/*



    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Access',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Accounting',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Bridge_BusinessOwner_Marketer',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Bridge_Invoice_Product',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Bridge_Province_BusinessOwner',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('BusinessOwner',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Category',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('CategorySetting',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Comment',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Content',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('DisputeResolution',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Entity',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Filed',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Invoice',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Languge',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Marketer',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Message',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Product',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Province',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Role',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('Setting',NULL)
    GO  
    
    
     
      INSERT INTO [ShoppingCenters].[Accsess].[Entity]
               ([Name]
               ,[PersianName])
             
         VALUES
               ('User',NULL)
    GO  
    
    */
    

