//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnarSoft.DataLayer.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Culture_fa_IR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Culture_fa_IR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnarSoft.DataLayer.App_GlobalResources.Culture-fa_IR", typeof(Culture_fa_IR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ممتنع.
        /// </summary>
        internal static string Abstained {
            get {
                return ResourceManager.GetString("Abstained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت آرامیکس.
        /// </summary>
        internal static string Aramex {
            get {
                return ResourceManager.GetString("Aramex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار پرداخت .
        /// </summary>
        internal static string BusinessOwnerAccept {
            get {
                return ResourceManager.GetString("BusinessOwnerAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy From.
        /// </summary>
        internal static string buy_From {
            get {
                return ResourceManager.GetString("buy_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو .
        /// </summary>
        internal static string Cancele {
            get {
                return ResourceManager.GetString("Cancele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو .
        /// </summary>
        internal static string canceled {
            get {
                return ResourceManager.GetString("canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحویل.
        /// </summary>
        internal static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        internal static string FalseValue {
            get {
                return ResourceManager.GetString("FalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهایی شد.
        /// </summary>
        internal static string Final {
            get {
                return ResourceManager.GetString("Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        internal static string initialize {
            get {
                return ResourceManager.GetString("initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملت.
        /// </summary>
        internal static string Melat {
            get {
                return ResourceManager.GetString("Melat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناراضی.
        /// </summary>
        internal static string NoSatisfied {
            get {
                return ResourceManager.GetString("NoSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط فروش اکسپرس دارم.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر شرکت  های حمل و نقل.
        /// </summary>
        internal static string OtherCo {
            get {
                return ResourceManager.GetString("OtherCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسارگاد.
        /// </summary>
        internal static string Pasargad {
            get {
                return ResourceManager.GetString("Pasargad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار ارسال.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت پست جمهوری اسلامی ایران.
        /// </summary>
        internal static string PostIran {
            get {
                return ResourceManager.GetString("PostIran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار تایید فروشنده.
        /// </summary>
        internal static string request {
            get {
                return ResourceManager.GetString("request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هر دو حالت فروش اکسپرس و درخواستی را دارم.
        /// </summary>
        internal static string RequestAndOnline {
            get {
                return ResourceManager.GetString("RequestAndOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط درخواست خرید قبول می کنم.
        /// </summary>
        internal static string RequestOnly {
            get {
                return ResourceManager.GetString("RequestOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راضی.
        /// </summary>
        internal static string Satisfied {
            get {
                return ResourceManager.GetString("Satisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  پیک خود فروشنده.
        /// </summary>
        internal static string ShippingWithBusinessOwner {
            get {
                return ResourceManager.GetString("ShippingWithBusinessOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت تیپاکس.
        /// </summary>
        internal static string Tepaxs {
            get {
                return ResourceManager.GetString("Tepaxs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقدام به پرداخت.
        /// </summary>
        internal static string ToPay {
            get {
                return ResourceManager.GetString("ToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت تی پی جی(TPG).
        /// </summary>
        internal static string TPG {
            get {
                return ResourceManager.GetString("TPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        internal static string TrueValue {
            get {
                return ResourceManager.GetString("TrueValue", resourceCulture);
            }
        }
    }
}
