//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnarSoft.DataLayer.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Culture_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Culture_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnarSoft.DataLayer.App_GlobalResources.Culture-en", typeof(Culture_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait payment user.
        /// </summary>
        internal static string BusinessOwnerAccept {
            get {
                return ResourceManager.GetString("BusinessOwnerAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy From.
        /// </summary>
        internal static string buy_From {
            get {
                return ResourceManager.GetString("buy_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canceled.
        /// </summary>
        internal static string canceled {
            get {
                return ResourceManager.GetString("canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to final or delivered.
        /// </summary>
        internal static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string FalseValue {
            get {
                return ResourceManager.GetString("FalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        internal static string initialize {
            get {
                return ResourceManager.GetString("initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melat.
        /// </summary>
        internal static string Melat {
            get {
                return ResourceManager.GetString("Melat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasargad.
        /// </summary>
        internal static string Pasargad {
            get {
                return ResourceManager.GetString("Pasargad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait Delivered.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait BusinessOwner Accept.
        /// </summary>
        internal static string request {
            get {
                return ResourceManager.GetString("request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string TrueValue {
            get {
                return ResourceManager.GetString("TrueValue", resourceCulture);
            }
        }
    }
}
