//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnarSoft.DataLayer.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyPesianName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyPesianName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnarSoft.DataLayer.App_GlobalResources.PropertyPesianName", typeof(PropertyPesianName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Abs_AccountingEntityAddress {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Abs_AccountingEntityCityName {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Abs_AccountingEntityEmail {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Abs_AccountingEntityId {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Abs_AccountingEntityIEnumerableProvince {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityIEnumerableProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Abs_AccountingEntityLinkBridge_Document_BusinessOwner {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityLinkBridge_Document_BusinessOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Abs_AccountingEntityMobile {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Abs_AccountingEntityName {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Abs_AccountingEntityNameAndFamilyOwner {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityNameAndFamilyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Abs_AccountingEntityProvince {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Abs_AccountingEntityRegisterDate {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Abs_AccountingEntityTel_1 {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityTel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Abs_AccountingEntityTel_2 {
            get {
                return ResourceManager.GetString("Abs_AccountingEntityTel_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Category_ProductCategory {
            get {
                return ResourceManager.GetString("Bridge_Category_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Bridge_Category_ProductId {
            get {
                return ResourceManager.GetString("Bridge_Category_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Category_ProductIEnumerableCategory {
            get {
                return ResourceManager.GetString("Bridge_Category_ProductIEnumerableCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Category_ProductIEnumerableProduct {
            get {
                return ResourceManager.GetString("Bridge_Category_ProductIEnumerableProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Category_ProductProduct {
            get {
                return ResourceManager.GetString("Bridge_Category_ProductProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Document_BusinessOwnerAbs_AccountingEntity {
            get {
                return ResourceManager.GetString("Bridge_Document_BusinessOwnerAbs_AccountingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Document_BusinessOwnercreditor {
            get {
                return ResourceManager.GetString("Bridge_Document_BusinessOwnercreditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Document_BusinessOwnerDebtor {
            get {
                return ResourceManager.GetString("Bridge_Document_BusinessOwnerDebtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Document_BusinessOwnerDocument {
            get {
                return ResourceManager.GetString("Bridge_Document_BusinessOwnerDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Bridge_Document_BusinessOwnerId {
            get {
                return ResourceManager.GetString("Bridge_Document_BusinessOwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Document_BusinessOwnerIEnumerableAbs_AccountingEntity {
            get {
                return ResourceManager.GetString("Bridge_Document_BusinessOwnerIEnumerableAbs_AccountingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Document_BusinessOwnerIEnumerableDocument {
            get {
                return ResourceManager.GetString("Bridge_Document_BusinessOwnerIEnumerableDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Invoice_ProductCount {
            get {
                return ResourceManager.GetString("Bridge_Invoice_ProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Bridge_Invoice_ProductId {
            get {
                return ResourceManager.GetString("Bridge_Invoice_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Invoice_ProductIEnumerableInvoice {
            get {
                return ResourceManager.GetString("Bridge_Invoice_ProductIEnumerableInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Invoice_ProductIEnumerableProduct {
            get {
                return ResourceManager.GetString("Bridge_Invoice_ProductIEnumerableProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Invoice_ProductInvoice {
            get {
                return ResourceManager.GetString("Bridge_Invoice_ProductInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Bridge_Invoice_ProductProduct {
            get {
                return ResourceManager.GetString("Bridge_Invoice_ProductProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string BusinessOwnerId {
            get {
                return ResourceManager.GetString("BusinessOwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string BusinessOwnerLinkProduct {
            get {
                return ResourceManager.GetString("BusinessOwnerLinkProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string CategoryCategory {
            get {
                return ResourceManager.GetString("CategoryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string CategoryDiscription {
            get {
                return ResourceManager.GetString("CategoryDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string CategoryIEnumerableCategory {
            get {
                return ResourceManager.GetString("CategoryIEnumerableCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string CategoryLinkBridge_Category_Product {
            get {
                return ResourceManager.GetString("CategoryLinkBridge_Category_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string CategoryLinkCategory {
            get {
                return ResourceManager.GetString("CategoryLinkCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string CategorySettingGroupName {
            get {
                return ResourceManager.GetString("CategorySettingGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string CategorySettingId {
            get {
                return ResourceManager.GetString("CategorySettingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string CategorySettingLinkSetting {
            get {
                return ResourceManager.GetString("CategorySettingLinkSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string CategorySettingName {
            get {
                return ResourceManager.GetString("CategorySettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ContentDisplayMode {
            get {
                return ResourceManager.GetString("ContentDisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ContentEntityName {
            get {
                return ResourceManager.GetString("ContentEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string ContentId {
            get {
                return ResourceManager.GetString("ContentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string ContentName {
            get {
                return ResourceManager.GetString("ContentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ContentPartialType {
            get {
                return ResourceManager.GetString("ContentPartialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Contentpriority {
            get {
                return ResourceManager.GetString("Contentpriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ContentRole {
            get {
                return ResourceManager.GetString("ContentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ContentWidth {
            get {
                return ResourceManager.GetString("ContentWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string DocumentId {
            get {
                return ResourceManager.GetString("DocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string DocumentIEnumerableInvoice {
            get {
                return ResourceManager.GetString("DocumentIEnumerableInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string DocumentInvoice {
            get {
                return ResourceManager.GetString("DocumentInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string DocumentLinkBridge_Document_BusinessOwner {
            get {
                return ResourceManager.GetString("DocumentLinkBridge_Document_BusinessOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string DocumentRefrenceNumber {
            get {
                return ResourceManager.GetString("DocumentRefrenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string FiledAccessEnums {
            get {
                return ResourceManager.GetString("FiledAccessEnums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string FiledEntityName {
            get {
                return ResourceManager.GetString("FiledEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string FiledId {
            get {
                return ResourceManager.GetString("FiledId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FiledName {
            get {
                return ResourceManager.GetString("FiledName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string FiledPersian {
            get {
                return ResourceManager.GetString("FiledPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string InvoiceId {
            get {
                return ResourceManager.GetString("InvoiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string InvoiceLinkBridge_Invoice_Product {
            get {
                return ResourceManager.GetString("InvoiceLinkBridge_Invoice_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string InvoiceLinkDocument {
            get {
                return ResourceManager.GetString("InvoiceLinkDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string InvoiceName {
            get {
                return ResourceManager.GetString("InvoiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string InvoicePaymentSum {
            get {
                return ResourceManager.GetString("InvoicePaymentSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string InvoiceState {
            get {
                return ResourceManager.GetString("InvoiceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string MarketerId {
            get {
                return ResourceManager.GetString("MarketerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string MarketerSpecialty {
            get {
                return ResourceManager.GetString("MarketerSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ProductBusinessOwner {
            get {
                return ResourceManager.GetString("ProductBusinessOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ProductDiscription {
            get {
                return ResourceManager.GetString("ProductDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ProductIEnumerableBusinessOwner {
            get {
                return ResourceManager.GetString("ProductIEnumerableBusinessOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ProductLinkBridge_Category_Product {
            get {
                return ResourceManager.GetString("ProductLinkBridge_Category_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ProductLinkBridge_Invoice_Product {
            get {
                return ResourceManager.GetString("ProductLinkBridge_Invoice_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string Provincecountry {
            get {
                return ResourceManager.GetString("Provincecountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string ProvinceId {
            get {
                return ResourceManager.GetString("ProvinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ProvinceLinkAbs_AccountingEntity {
            get {
                return ResourceManager.GetString("ProvinceLinkAbs_AccountingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string ProvinceLinkUser {
            get {
                return ResourceManager.GetString("ProvinceLinkUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string ProvinceName {
            get {
                return ResourceManager.GetString("ProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string SettingCategorySetting {
            get {
                return ResourceManager.GetString("SettingCategorySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string SettingId {
            get {
                return ResourceManager.GetString("SettingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string SettingIEnumerableCategorySetting {
            get {
                return ResourceManager.GetString("SettingIEnumerableCategorySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string SettingName {
            get {
                return ResourceManager.GetString("SettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string SettingValue {
            get {
                return ResourceManager.GetString("SettingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string UserAddress {
            get {
                return ResourceManager.GetString("UserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string UserCityName {
            get {
                return ResourceManager.GetString("UserCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string UserFamily {
            get {
                return ResourceManager.GetString("UserFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string UserIEnumerableProvince {
            get {
                return ResourceManager.GetString("UserIEnumerableProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string UserMobile {
            get {
                return ResourceManager.GetString("UserMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string UserProvince {
            get {
                return ResourceManager.GetString("UserProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string UserRegisterDate {
            get {
                return ResourceManager.GetString("UserRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسن.
        /// </summary>
        public static string UserTel {
            get {
                return ResourceManager.GetString("UserTel", resourceCulture);
            }
        }
    }
}
