
//------------------------------------------------------------------------------
// <auto-generated>
// by mehrang 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
//using System.Data.Objects;
//using System.Data.Objects.DataClasses;
//using System.Data.EntityClient;
using DataLayer;
using DataLayer.EF;

namespace ServiceLayer
{
    public class Contract
    {
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AccessService : DataRepository<Access>
    {
        public AccessService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AccountingService : DataRepository<Accounting>
    {

    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Bridge_Category_ProductService : DataRepository<Bridge_Category_Product>
    {
        public Bridge_Category_ProductService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Bridge_Invoice_ProductService : DataRepository<Bridge_Invoice_Product>
    {
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BusinessOwnerService : DataRepository<BusinessOwner>
    {
        public BusinessOwnerService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CategoryService : DataRepository<Category>
    {
        public CategoryService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CategorySettingService : DataRepository<CategorySetting>
    {
        public CategorySettingService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ContentService : DataRepository<Content>
    {
        public ContentService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EntityService : DataRepository<Entity>
    {
        public EntityService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FiledService : DataRepository<Filed>
    {
        public FiledService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InvoiceService : DataRepository<Invoice>
    {

    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LangugeService : DataRepository<Languge>
    {
        public LangugeService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MarketerService : DataRepository<Marketer>
    {
        public MarketerService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProductService : DataRepository<Product>
    {
        public ProductService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProvinceService : DataRepository<Province>
    {
        public ProvinceService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RoleService : DataRepository<Role>
    {
        public RoleService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SettingService : DataRepository<Setting>
    {
        public SettingService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class UserService : DataRepository<User>
    {
        public UserService(OnlineShopping OnlineShopping) : base(OnlineShopping)
        {
        }
    }



}
