
//------------------------------------------------------------------------------
// <auto-generated>
// by mehrang 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using DataLayer;
using System.Collections.Generic;
using System.Web;
using DataLayer.Enums;
using DataLayer.EF;

namespace ServiceLayer
{
    public class Contract
    {
    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Bridge_BusinessOwner_MarketerService : BaseService<BridgeBusinessOwnerMarketer>
    {
        public Bridge_BusinessOwner_MarketerService(OnlineShopping OnlineShopping)
            : base(OnlineShopping)
        {
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Bridge_Province_BusinessOwnerService : BaseService<BridgeProvinceBusinessOwner>
    {
        public Bridge_Province_BusinessOwnerService(OnlineShopping OnlineShopping)
            : base(OnlineShopping)
        {
        }
    }


    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>



    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Bridge_Invoice_ProductService : BaseService<BridgeInvoiceProduct>
    {
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BusinessOwnerService : BaseService<BusinessOwner>
    {

    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CategoryService : BaseService<Category>
    {



    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>



    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InvoiceService : BaseService<Invoice>
    {

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MarketerService : BaseService<Marketer>
    {

    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProductService : BaseService<Product>
    {

    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProvinceService : BaseService<Province>
    {

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class UserService : BaseService<User>
    {
        //public UserService(OnlineShopping OnlineShopping)
        //    : base(OnlineShopping)
        //{
        //}
    }
   
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CommentService : BaseService<Comment>
    {
        public CommentService(OnlineShopping OnlineShopping)
            : base(OnlineShopping)
        {
        }
    }

    public partial class DisputeResolutionService : BaseService<DisputeResolution>
    {
        public DisputeResolutionService(OnlineShopping OnlineShopping)
            : base(OnlineShopping)
        {
        }
    }
    //
    public partial class MessageService : BaseService<Message>
    {

    }
}
